
--EJ1
DROP TABLE EMPLEADOS30;
CREATE TABLE EMPLEADOS30
AS
SELECT*
FROM EMPLE
WHERE DEPT_NO =30;

DESC EMPLEADOS30;
SELECT * FROM EMPLEADOS30;

SELECT CONSTRAINS_TYPE,CONSTRAINS_NAME,USERS_CONS_COLUMNS.*
FROM USER_CONSTRAINTS,user_cons_columns
WHERE USER_CONSTRAINTS.CONSTRAINT_NAME=USERS_CONS_COLUMNS.CONSTRAINT_NAME
AND UPPER(USER_CONSTRAINTS.TABLE_NAME)='EMPLEADOS30';
--NO COPIA LAS CONSTRAINTS

--1
INSERT INTO EMPLE(EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALTA,SALARIO,COMISION_PCT,DEPT_NO)
SELECT 200,'SAAVEDRA',OFOCOP,DIR,SYSDATE
    ,SALARIO/SALARIO*0.2,COMISION_PCT,DEPT_NO
FROM EMPLE
WHERE UPPER(APELLIDO)='SALA';


--2
UPDATE EMPLE
SET DEPT_NO=(SELECT DEPT_NO
            FROM EMPLE
            WHERE EMP_NO=74999)
WHERE OFICIO=(SELECT OFICIO
              FROM EMPLE
              WHERE EMP_NO=7566);
            

--3         
DELETE FROM DEPART
WHERE dept_no NOT IN
(SELECT DISTINCT DEPT_NO  FROM EMPLE);
        
        
 --4
 DELETE FROM EMPLE
WHERE dept_no  IN(SELECT DEPT_NO  
                 FROM DEPART
                 WHERE UPPER(DNOMBRE) LIKE'%O%');
        
        
        
        
--5
UPDATE EMPLE
SET SALARIO= SALARIO+(SELECT NVL(COMISION_PCT,0)
                     FROM EMPLE
                     WHERE UPPER(APELLIDO)='ARROYO')
WHERE UPPER(APELLIDO)='REY';
        



rollback;